DROP DATABASE IF EXISTS california_users;
CREATE DATABASE california_users;

\c california_users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  email VARCHAR NOT NULL UNIQUE,
  phone_number VARCHAR NOT NULL UNIQUE
);

CREATE TABLE photos (
  id SERIAL PRIMARY KEY,
  url VARCHAR NOT NULL,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  photo_id INT REFERENCES photos(id) ON DELETE CASCADE
);
